version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo_container_LeGoat
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend: 
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container_LeGoat
    ports:
      - "3000:3000" # или порт твоего backend
    environment:
      MONGO_URI: "mongodb://mongo:27017/sneakershop"
    depends_on:
      - mongo

volumes:
  mongo_data:
